""""""""""""""""""""""""""""""""""""""""""""
""            vimrc file
"" https://github.com/techyArsal/dotfiles
""""""""""""""""""""""""""""""""""""""""""""

"" Note - Now I use neovim as my editor, so this config file is not in use anymore

set nocompatible
set encoding=utf-8
filetype off

"""""""""""""""""""""""""""""""""
"" VimPlug config
"""""""""""""""""""""""""""""""""

"" All of your Plugin enteries must be between
"" call plug#begin() and call plug#end() block

call plug#begin('~/.vim/plugins')   " required

"Plug 'preservim/nerdtree'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdcommenter'
Plug 'ap/vim-css-color'
Plug 'mg979/vim-visual-multi', {'branch': 'master'}
Plug 'mattn/emmet-vim'
Plug 'kyoz/purify', { 'rtp': 'vim' }
Plug 'sainnhe/sonokai'
Plug 'sainnhe/edge'
Plug 'dense-analysis/ale'
Plug 'ryanoasis/vim-devicons'

call plug#end()            " required

"" Put your non-Plugin stuff after this line

"""""""""""""""""""""""""""""""""
"" My configs
"""""""""""""""""""""""""""""""""

filetype plugin indent on
syntax on
colorscheme purify
"colorscheme sonokai

"" Spell checking
set nospell
set spelloptions="camel"
set spelllang=en_us
"set spelllang=en_us,en_ca,en_gb,en_au,en_nz

"" Search down into subfolders
"" Provides tab-completion for all file-related tasks
set path+=**

"" Display all matching files when we tab complete
set wildmenu

"" FILE BROWSING:
""
"" Tweaks for browsing
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
""
"" NOW WE CAN:
"" - :edit a folder to open a file browser
"" - <CR>/v/t to open in an h-split/v-split/tab
"" - check |netrw-browse-maps| for more mappings

"" Searching and Highlighting
set number relativenumber
set cursorline
set showcmd
set showmatch
set incsearch
set termguicolors

"" keep more info in memory
set hidden
set history=1000

"" Enable persistent undo in vim
set undofile
set undodir=~/.vim/undo

"" Automatically save file
autocmd FocusLost * silent! wa

"" Indentation and stuff
set tabstop=4
set shiftwidth=4
set expandtab
set smartindent
set autoindent
set modelines=10
set scrolloff=5
set breakindent

"" Start Rainbow plugin
"let g:rainbow_active=1

"" Airline Configs
let g:airline_theme='purify'
let g:airline_powerline_fonts=1
let g:airline_detect_modified=1
let g:airline_detect_paste=1
let g:airline_detect_crypt=1
let g:airline_detect_spell=1
let g:airline_inactive_collapse=1
let g:airline_skip_empty_sections=1
let g:airline_highlighting_cache=1
"let g:airline#parts#ffenc#skip_expected_string='utf-8[unix]'

set ttimeoutlen=50

"" Remember position of last edit and return on reopen
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

"" ALE configs
let g:ale_lint_on_enter=0
let g:ale_sign_error = '●'
let g:ale_sign_warning = '.'

"""""""""""""""""""""""""""""""""
"" key-bindings - shortcuts
"""""""""""""""""""""""""""""""""

"" setting space-key as leader-key
let mapleader=" "

"" space+s to source vimrc
map <leader>s :source ~/.vim/vimrc<CR>

"" default navigation-keys to arrow-keys
"map <D-A-RIGHT> <C-w>l
"map <D-A-LEFT> <C-w>h
"map <D-A-DOWN> <C-w><C-w>
"map <D-A-UP> <C-w>W

"" press space-key twice to open the previous file
"nnoremap <Leader><Leader> :e#<CR>
set secure
